[project]
name = "xtbscan2-gpu"
version = "0.5.0"
description = "GUI tool for structural optimization and scan calculations using xtb or fairchem-core (GPU enabled)."
readme = "../README.md"
requires-python = ">=3.11"
authors = [
    { name = "Tatsuhiko Yoshino" }
]
dependencies = [
    "fairchem-core",
    "torch",
    "ase",
    "pyside6>=6.11.1",
    "numpy",
    "scipy",
    "cclib",
    "matplotlib"
]

[tool.uv]
compile-bytecode = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
